site_name: Portal de Documenta√ß√£o do LiviuHub
site_url: https://adaptedtech.github.io/liviu-docs/docs/

theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  language: pt-BR
  palette:
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    # - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
extra:
  mermaid: true  # üî• habilita suporte nativo ao Mermaid no Material


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid      # habilita bloco ```mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  
nav:
  - In√≠cio: index.md

  - Liviu Analytics:
      - Usu√°rio:
        - Vis√£o geral: liviu-analytics/index.md
        - Primeiros passos: liviu-analytics/user/first-access.md
        - Guia do usu√°rio: liviu-analytics/user/user-guide.md
        - Fluxos: liviu-analytics/user/flow.md
        - FAQ: liviu-analytics/user/faq.md
      - Tecnologia:
        - Arquitetura: liviu-analytics/tech/architecture.md
        - Frontend: liviu-analytics/tech/frontend.md
        - API: liviu-analytics/tech/api.md
        - Banco de dados: liviu-analytics/tech/database.md
        - Integra√ß√µes: liviu-analytics/tech/integrations.md

  - Liviu Content:
      - Usu√°rio:
        - Vis√£o geral: liviu-content/index.md
        - Guia do usu√°rio: liviu-content/user/user-guide.md
        - Fluxos: liviu-content/user/flow.md
        - FAQ: liviu-content/user/faq.md
      - Tecnologia:
        - Arquitetura: liviu-content/tech/architecture.md
        - Frontend: liviu-content/tech/frontend.md
        - API: liviu-content/tech/api.md
        - Banco de dados: liviu-content/tech/database.md
        - Integra√ß√µes: liviu-content/tech/integrations.md

  - Liviu Flow:
      - Usu√°rio: 
        - Vis√£o geral: liviu-flow/index.md
        - Guia do usu√°rio: liviu-flow/user/user-guide.md
        - Fluxos: liviu-flow/user/flow.md
        - FAQ: liviu-flow/user/faq.md
      - Tecnologia:
        - Arquitetura: liviu-flow/tech/architecture.md
        - Frontend: liviu-flow/tech/frontend.md
        - API: liviu-flow/tech/api.md
        - Banco de dados: liviu-flow/tech/database.md
        - Integra√ß√µes: liviu-flow/tech/integrations.md